#!/bin/bash

# generate the rom image and the data image, it will be up to either the MCU or
# the MPU to load the data section into the proper place in ram

i960-elf-objcopy --only-section=.text -O binary cmake-build-debug/hitagimon boot.rom
i960-elf-objcopy --only-section=.data -O binary cmake-build-debug/hitagimon boot.dat
